{{ if .Values.serviceAccount.create }}

apiVersion: v1
kind: ServiceAccount
metadata:
  name:  {{ template "uni-academy.serviceAccountName" . }} 

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-role
rules:
- apiGroups: ["*"] # empty "" api group indicates the core API group
  resources: ["pods","deployments"]
  verbs: ["get","list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-rolebinding
subjects:
# You can specify more than one "subject"
- kind: ServiceAccount
  name: {{ template "uni-academy.serviceAccountName" . }} 
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: Role #this must be Role or ClusterRole
  name: {{ .Release.Name }}-role # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io

{{ end }}