apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: uni-academy-service-binding
subjects:
# You can specify more than one "subject"
- kind: ServiceAccount
  name: uni-academy
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: Role #this must be Role or ClusterRole
  name: uni-academy-service # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io