kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

bases:
  - "../base"

namespace: alysina

replicas:
  - name: uni-academy
    count: 3

images:
  - name: acruniacademy.azurecr.io/uni-academy
    newTag: 1.0.0

patches:
  - path: './resource_request.patch.yaml'
    target:
      kind: Deployment
      name: uni-academy
  - path: './config.patch.yaml'
    target:
      kind: ConfigMap
      name: uni-academy