kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

bases:
  - "../base"

namespace: alysina-dev

replicas:
  - name: uni-academy
    count: 3

images:
  - name: acruniacademy.azurecr.io/uni-academy
    newTag: latest